# Generated by Django 3.2.9 on 2022-02-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharNo', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('res_addr', models.CharField(max_length=100)),
                ('native_pl', models.CharField(max_length=100)),
                ('mob_no', models.IntegerField()),
            ],
        ),
    ]
