# Generated by Django 3.2.9 on 2022-02-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelmember',
            old_name='aadharNo',
            new_name='Aadhar_No',
        ),
        migrations.RenameField(
            model_name='hostelmember',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='hostelmember',
            old_name='mob_no',
            new_name='Mobile_No',
        ),
        migrations.RenameField(
            model_name='hostelmember',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='hostelmember',
            old_name='native_pl',
            new_name='Native_Place',
        ),
        migrations.RenameField(
            model_name='hostelmember',
            old_name='res_addr',
            new_name='Residential_Address',
        ),
    ]
